// Vendored Capacitor dependencies (not from node_modules)
include ':capacitor-android'
project(':capacitor-android').projectDir = new File('./capacitor-android-vendored')

include ':revenuecat-purchases-capacitor'
project(':revenuecat-purchases-capacitor').projectDir = new File('./revenuecat-vendored')
